version: '3'
services:
  db:
    image: postgres
  rails:
    build: .
    volumes:
      - .:/myapp:cached
    ports:
      - "5000:3000"
    depends_on:
      - db
  webpacker:
    build: .
    entrypoint: ./bin/webpack-dev-server
    volumes:
      - .:/myapp:cached
    ports:
      - "8080:8080"
    depends_on:
      - db
