version: '2'
services:
  db:
    image: postgres
  rails:
    build: .
    volumes:
      - sync-volume:/myapp:nocopy
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpacker:
    build: .
    entrypoint: ./bin/webpack-dev-server
    volumes:
      - sync-volume:/myapp
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  sync-volume:
    external: true
